### ISSUE TITLE
Standard page when web service is called without, wrong, or missing parameters

### ISSUE THREAD

**Issue by athalhammer** [WDAqua/SummaServer#2]
It would be good to have a standard page that explains usage of the service as default for the 

./{KB}

and 

./{KB}/sum

subpages (e.g. when arguments are missing). Like a page explaining the service access in high level.

**Comment by athalhammer** [comment]
@D063520 

The page is working now with "sum":

* https://wdaqua-summa-server.univ-st-etienne.fr/dbpedia/sum

but not without:

* https://wdaqua-summa-server.univ-st-etienne.fr/dbpedia

**Comment by D063520** [comment]
Issue solved
